### ISSUE TITLE
Position additional information

### ISSUE THREAD

**Issue by ghost** [FoxelSA/rawdata-navigator#2]
I'm fond of rawdata-navigator new design !

By the way, it could be nice to specify on the information panel that longitudes and latitudes are expressed in WGS84 ellispoïde when altitude is the orthometric altitude above reference geoïd (MSL). Something like : 

Latitude (WGS84) : some latitude
...
Altitude (MSL) : some altitude

**Comment by prston** [comment]
Thank you. Now fixed on the master branch.
